# Generated by Django 3.0.3 on 2020-02-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200217_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('warehouseId', models.IntegerField(default=0, verbose_name='归属仓库id')),
                ('location', models.CharField(default='', max_length=150, verbose_name='坐标')),
                ('url', models.CharField(default='', max_length=150, verbose_name='访问地址')),
                ('extension', models.CharField(default='', max_length=150, verbose_name='扩展字段')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
