# Generated by Django 3.0.2 on 2020-02-27 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('sensorId', models.IntegerField(default=0, verbose_name='传感器id')),
                ('value', models.IntegerField(default=0, verbose_name='值')),
                ('normal', models.IntegerField(default=1, verbose_name='是否正常')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='abnormal',
            field=models.CharField(default='', max_length=150, verbose_name='异常表达式'),
        ),
    ]
