# Generated by Django 3.0.2 on 2020-03-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200228_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='sync_num',
            field=models.IntegerField(default=0, verbose_name='从边缘设备批量同步监控数据的条数'),
        ),
    ]
